// Lesson 04 playground

import Foundation

// TODO: Create two variables, name and age. Name is a string, age is an integer.

var Name: String = "Monica"
var Age = 22

// TODO: Print "Hello {whatever the value of name is}, you are {whatever the value of age is} years old!"

println ("Hello \(Name), you are \(Age) years old")

// TODO: Print “You can drink” below the above text if the user is above 21. If they are above 18, print “you can vote”. If they are above 16, print “You can drive”

if Age > 21 {
    println ("You can drink")
}else if Age > 18 {
    println ("You can vote")
}else if Age > 16 {
    println ("You can drive")
}

// TODO: Print “you can drive” if the user is above 16 but below 18. It should print “You can drive and vote” if the user is above 18 but below 21. If the user is above 21, it should print “you can drive, vote and drink (but not at the same time!”.

if Age > 16 && Age < 18 {
    println ("You can drive")
} else if Age > 18 && Age < 21 {
    println ("You can drive and vote")
} else if Age > 21 {
    println ("You can drive, vote and drink (but not at the same time!)")
}

// TODO: Print the first fifty multiples of seven minus one (e.g. the first three multiples are 7, 14, 21. The first three multiples minus one are 6, 13, 20)

for index in 1...50 {
    var seven = index*7
    var six = seven-1
    println(six)
}

// TODO: Create a constant called number

let number = 15

// TODO: Print whether the above number is even

var remainder = number % 2

if remainder == 1 {
    println ("the number is odd")
} else {
    println ("the number is even")
}

// TODO: The first fibonacci number is 0, the second is 1, the third is 1, the fourth is two, the fifth is 3, the sixth is 5, etc. The Xth fibonacci number is the sum of the X-1th fibonacci number and the X-2th fibonacci number. Print the 37th fibonacci number below

// fibonacci: 0 1 1 2 3 5 8 13 21 34 55
// F(x) = F(x-1) + F(x-2) so F(5) = F(4) + F(3) => 5 = 3+2, 3 = 2+1

var count = 3
var prior = 0
var follow = 1
var fib = prior + follow

while count < 37 {
    println ("the fibonnaci number at position \(count) is \(fib)")
    prior = follow
    follow = fib
    fib = prior + follow
    ++count
}

fib
println ("The 37th fibonacci number is \(fib)")

// TODO: Print out "Hello {whatever the value of name is}, your name is {however long the string name is} characters long!. Use countElements()

var character = countElements(Name)

println ("Hello \(Name), your name is \(character) characters long!")

// TODO: Print the sum of one hundred random numbers. Use rand() to generate random numbers.

var RandomNum = Int(rand())
var base = Int(0)
var sum = Int(0)

for index in 1...10 {
    RandomNum = Int(rand())
    println ("Random Number \(index) is \(RandomNum)")
    sum = RandomNum + base
    base = RandomNum
    println ("Sum is \(sum)")
}

sum

println ("The sum of ten random numbers generated by using rand () is \(sum)")

base = 0
sum = 0

for index in 1...100 {
    RandomNum = Int(rand())
    sum = RandomNum + base
    base = RandomNum
}

sum

println ("The sum of one hundred random numbers generated by using rand () is \(sum)")

// Bonus TO DO: Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

var mult3 = 0
var mult5 = 0
var both = 0

for index in 1...100 {
    mult3 = index % 3
    mult5 = index % 5
    both = mult3 + mult5
    if both == 0 {
        println ("FizzBuzz")
    } else if mult3 < 1 {
        println ("Fizz")
    } else if mult5 < 1 {
        println ("Buzz")
    } else {
        println (index)
    }}



